spring.application.name=gym_ms

# Server Configuration
server.port=8080
server.servlet.context-path=/

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/gym_membership_db
spring.datasource.username=postgres
spring.datasource.password=123abc
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=GymMembershipSystemSecretKeyForJWTTokenGenerationAndValidationPurpose2024
jwt.expiration=86400000

# Logging
logging.level.root=INFO
logging.level.com.g_3.gym_ms=DEBUG
logging.level.org.springframework.security=DEBUG
